[theme.overrides]
info_bg = "#FCFF00"
info_fg = "#232c31"
idle_bg = "#232c31"
idle_fg = "#EBEBEB"
good_bg = "#FF214E"
good_fg = "#232c31"
warning_bg = "#0EE9F7"
warning_fg = "#232c31"
critical_bg = "#0EE9F7"
critical_fg = "#232c31"
separator_bg = "auto"
separator_fg = "auto"
