idle_bg = "#292d3e"
idle_fg = "#d0d0d0"
info_bg = "#82aaff"
info_fg = "#292d3e"
good_bg = "#c3e88d"
good_fg = "#292d3e"
warning_bg = "#bffcb6"
warning_fg = "#292d3e"
critical_bg = "#f07178"
critical_fg = "#292d3e"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"
